name: Build VIP BINPRO
on: [push]

jobs:
  build:
    runs-on: macos-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4 # Cập nhật lên v4

      - name: Setup Theos
        run: |
          bash -c "$(curl -fsSL https://raw.githubusercontent.com/theos/theos/master/bin/install-theos)"
          
      - name: Build Dylib
        run: |
          export THEOS=$HOME/theos
          make package FINALPACKAGE=1
          
      - name: Luu file dylib
        uses: actions/upload-artifact@v4 # ĐÃ SỬA CHỖ NÀY THÀNH V4
        with:
          name: VIP_BINPRO_DYLIB
          path: .theos/obj/*.dylib
